org: j41r0
app: e-jairo
service: auth-service

provider:
  name: aws
  runtime: nodejs18.x
  esbuild: true
  environment:
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

functions:
  signUpUser:
    handler: src/handler.signUpUser
    events:
      - httpApi:
          path: /signup
          method: post

plugins:
  - serverless-offline