org: j41r0
app: e-jairo
service: auth-service

provider:
  name: aws
  runtime: nodejs18.x
  esbuild: true

functions:
  testHelloWorld:
    handler: src/handler.testHelloWorld
    url: true

plugins:
  - serverless-offline